wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.5
    framework: lightgbm
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724229527
    t:
      1:
      - 5
      - 6
      - 8
      - 53
      - 55
      - 69
      - 105
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      - 69
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.11.5
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
num_users:
  desc: null
  value: 100
num_items:
  desc: null
  value: 500
num_latent_factors:
  desc: null
  value: 15
reg_param:
  desc: null
  value: 0.1
num_iterations:
  desc: null
  value: 10
