wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724231204
    t:
      1:
      - 55
      - 69
      - 105
      2:
      - 5
      - 6
      - 8
      - 53
      - 55
      - 69
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.17.5
      8:
      - 3
      - 5
      13: windows-amd64
    framework: lightgbm
